### ISSUE TITLE
Пожелания по функционалу

### ISSUE THREAD

**Issue by 777Raim** [hitman249/wine-launcher#1]
Во-первых, спасибо за работу!

Во-вторых, есть ряд предложений, касательно интерфейса: 
1. Добавить кнопку выхода из приложения (для увеличения производительности, запускаю данный лаунчер в отдельном Х-сервере и для закрытия приходится завершать сессию)
2. При работе с патчами не хватает информации о статусе выполнения команд. Сейчас чтобы узнать выполнились ли команды и есть ли ошибки, нужно идти в логи. Не очень удобно. Идеально было бы видеть лог выполнения как в терминале (читай в режиме реального времени) или после завершения выполнения команд в окне программы

Спасибо

**Comment by hitman249** [comment]
> Добавить кнопку выхода из приложения (для увеличения производительности, запускаю данный лаунчер в отдельном Х-сервере и для закрытия приходится завершать сессию)

Не очень понял, зачем?   
Во первых, лаунчер считает сколько времени провели в игре.
Во вторых, если его закрыть, то он перед своим выходом размонтирует все образы (с wine, games) и завершит игру.
Также, в его обязанности входит следить не зависла ли игра, не завис ли wine, восстановилось ли разрешение экрана после завершения игры, и прочее.

Давай лучше разберёмся в первоисточнике проблемы, зачем запускать лаунчер в отдельном x-сервере?

**Comment by 777Raim** [comment]
> Давай лучше разберёмся в первоисточнике проблемы, зачем запускать лаунчер в отдельном x-сервере?

Ноутбук у меня не особо производительный и для того, чтобы выиграть 20-30, а порой и 50% ФПС, запускаю игры в отдельном Х-сервере.

Лаунчер никто и не собирается закрыть во время игры. А вот для того, чтобы уже после игры закрыть лаунчер, приходится аварийно закрывать Х-сервер (т.к. оконного менеджера то нет и кнопки закрыть тоже) и, соответственно, лаунчер не размонтирует образы wine и games, и тоже аварийно закрывается. Это неправильно

**Comment by hitman249** [comment]
А если саму игру запустить на отдельном x-сервере ?
А лаунчер оставить в обычном

**Comment by 777Raim** [comment]
Каким образом это можно сделать? Куда писать параметр?

Опишу как я запускаю: перехожу в другую tty, логинюсь и запускаю
`startx /path/to/game/bin/start`
Знаю можно через основную сессию через терминал
`programm -- :1`
но мне лень было это все настраивать, уже привык через tty

Может имеет смысл  просто добавить горячую клавишу закрытия 'CTRL+Q'?

**Comment by hitman249** [comment]
В версии [Wine Launcher Version 1.3.6](https://github.com/hitman249/wine-launcher/releases/tag/v1.3.6) появилась кнопка выхода

**Comment by 777Raim** [comment]
> появилась кнопка выхода

Уже опробовал, спасибо!

**Comment by hitman249** [comment]
Продолжение в #2
