### ISSUE TITLE
Проблема при подготовке к сжатию игры

### ISSUE THREAD

**Issue by LokiGT** [hitman249/wine-launcher#10]
В разделе упаковка, RW директории, при установке переключателя напротив папки с игрой и нажатии сохранить происходит бесконечный процесс принятия изменеий. Если закрыть приложение и снова открыть, произвести сжатие игры, игра перестает запускаться. С остальными игрыми таких проблем нет. Игра: street legal racing. В папке с игрой имеется огромное количество папок и файлов. Подскажите какую информацию можно направить для выяснения причин данной проблемы?

**Comment by hitman249** [comment]
Добрый день.
Во первых, почему вы решили что приложение зависло?
Если файлов действительно много, то воссоздание структуры на симлинках может занять и пол часа.
Вы можете посмотреть в **консоли**, что ошибки не падают, для этого нужно запустить лаунчер так:
```sh
env debug=1 ./start
```
Также, слишком большое количество файлов, негативно влияют на время монтирования `squashfs` образа, поэтому я бы рекомендовал в конце ту жирную директорию с сотнями тысяч файлов удалить и вручную кинуть симлинк на эту директорию

**Comment by LokiGT** [comment]
Не то что бы зависло конечно, но оно ни в файлы не писало не проявляло какой либо другой активности. Попробую запустить дебаг.

**Comment by LokiGT** [comment]
Получилось только создав отделный симлинк на сохранения в папке с игрой (было бы удобно если бы это делалось из интерфейса приложения). Сама игра в 50к файлов без проблем сжимается и работает. Можно считать проблему решенной.
