### ISSUE TITLE
Appimagelauncher interferes with wine-launcher

### ISSUE THREAD

**Issue by Ahmed-E-86** [hitman249/wine-launcher#13]
I have `appimagelauncher` installed on my system, and I use it to open .appimage files on my system, and it works quite fine, but when I use it to open wine-launcher, I get these errors in the terminal:

```
wine: chdir to /run/user/1000/appimagelauncherfs/prefix : No such file or directory
wine: chdir to /run/user/1000/appimagelauncherfs/prefix : No such file or directory
ln: failed to create symbolic link '/run/user/1000/appimagelauncherfs/prefix/drive_c/Games': No such file or directory
```

wine-launcher is not aware that it is run by another application, and that is the cause of this issue.

**Comment by probonopd** [comment]
cc @TheAssassin

**Comment by Bitwolfies** [comment]
Strange, appimagelauncher didnt even try to manage this project, yet you still tell me I need to "uninstall it", did they blacklist it?

**Comment by hitman249** [comment]
I do not follow this project, but at that time they completely blocked the normal operation of many AppImage applications.  
For which they earned fame, to some extent, more like malware than something useful.  
I tried to negotiate with them and implemented what they asked, but it did not help at that time.  
Perhaps the situation has changed, but I do not want to mock my users.  

In general, AppimageLauncher intercepts many system calls and behaves like a complete malware.
Its even from the system is not easy to remove.
Of course it is not malware, but I would still prefer to stay away from it.
