### ISSUE TITLE
Error on game/application launching

### ISSUE THREAD

**Issue by HappyCampero76** [hitman249/wine-launcher#20]
Hi i have a small problem,i moved the game to the specified folder /data/,installed all prefix needed prepped and ready to luanch but....when i go to launch the game i get this error : 

_**[Wine Launcher] Run command:
 sh -c "export LD_LIBRARY_PATH=\"/home/maddog76/Wine-Launcher/bin/libs/i386:/home/maddog76/Wine-Launcher/bin/libs/x86-64:$LD_LIBRARY_PATH\" VK_LAYER_PATH=\"$VK_LAYER_PATH:/home/maddog76/Wine-Launcher/data/cache/implicit_layer.d\" XDG_CACHE_HOME=\"/home/maddog76/Wine-Launcher/data/cache\" WINE=\"wine\" WINE64=\"wine64\" WINEPREFIX=\"/home/maddog76/Wine-Launcher/prefix\" WINESERVER=\"wineserver\" WINEARCH=\"win64\" WINEDEBUG=\"-all\" WINESTART=\"C:\\windows\\command\\start.exe\" WINEDLLOVERRIDES=\"\" LC_ALL=\"it_IT.UTF-8\" DXVK_CONFIG_FILE=\"/home/maddog76/Wine-Launcher/prefix/drive_c/dxvk.conf\" DXVK_STATE_CACHE_PATH=\"/home/maddog76/Wine-Launcher/prefix/drive_c/cache\" DXVK_LOG_PATH=\"/home/maddog76/Wine-Launcher/prefix/drive_c/logs\" WINEESYNC=\"1\" WINEFSYNC=\"1\" STAGING_SHARED_MEMORY=\"1\" WINE_LARGE_ADDRESS_AWARE=\"1\" vblank_mode=\"0\" mesa_glthread=\"true\" DXVK_HUD=\"fps,devinfo\" && cd \"/home/maddog76/Wine-Launcher\" && cd \"/home/user/Wine-Launcher/prefix/drive_c/Games/The Super Game\" &&  \"wine\"  \"AoEDE.exe\" "**_

**_sh: 1: cd: can't cd to /home/user/Wine-Launcher/prefix/drive_c/Games/The Super Game_**

If i am not mistaken the program cannot _**"cd"**_ to specified folder,stating that i am a noob using linux that error to me seems something regarding the application.
in case that someone asks if i have given the right permission to the exec yes i did in the property of the application.
I wonder how do i overcome this issue?.
Thanks in advance for any help fixing my problem.

**Comment by hitman249** [comment]
1) Go to directory `/home/maddog76/Wine-Launcher/data/games/`
2) Create a directory in it `Age of Empires Definitive Edition`
3) Move your game into it
4) Run `start` file
5) Prefix > Games > Edit > Folder tab > Path (first field) > `Age of Empires Definitive Edition` > Save

**Comment by HappyCampero76** [comment]
>     1. Go to directory `/home/maddog76/Wine-Launcher/data/games/`
> 
>     2. Create a directory in it `Age of Empires Definitive Edition`
> 
>     3. Move your game into it
> 
>     4. Run `start` file
> 
>     5. Prefix > Games > Edit > Folder tab > Path (first field) > `Age of Empires Definitive Edition` > Save

Ok and thanks very much for the quick reply,now i popped up another issue:

[Wine Launcher] Run command:
 sh -c "export LD_LIBRARY_PATH=\"/home/maddog76/Wine-Launcher/bin/libs/i386:/home/maddog76/Wine-Launcher/bin/libs/x86-64:/home/maddog76/Wine-Launcher/wine/lib/wine:/home/maddog76/Wine-Launcher/wine/lib64/wine:$LD_LIBRARY_PATH\" VK_LAYER_PATH=\"$VK_LAYER_PATH:/home/maddog76/Wine-Launcher/data/cache/implicit_layer.d\" XDG_CACHE_HOME=\"/home/maddog76/Wine-Launcher/data/cache\" WINE=\"/home/maddog76/Wine-Launcher/wine/bin/wine\" WINE64=\"/home/maddog76/Wine-Launcher/wine/bin/wine64\" WINEPREFIX=\"/home/maddog76/Wine-Launcher/prefix\" WINESERVER=\"/home/maddog76/Wine-Launcher/wine/bin/wineserver\" WINEARCH=\"win64\" WINEDEBUG=\"-all\" WINESTART=\"C:\\windows\\command\\start.exe\" WINEDLLOVERRIDES=\"\" WINEDLLPATH=\"/home/maddog76/Wine-Launcher/wine/lib/wine:/home/maddog76/Wine-Launcher/wine/lib64/wine\" LC_ALL=\"it_IT.UTF-8\" DXVK_CONFIG_FILE=\"/home/maddog76/Wine-Launcher/prefix/drive_c/dxvk.conf\" DXVK_STATE_CACHE_PATH=\"/home/maddog76/Wine-Launcher/prefix/drive_c/cache\" DXVK_LOG_PATH=\"/home/maddog76/Wine-Launcher/prefix/drive_c/logs\" WINEESYNC=\"1\" WINEFSYNC=\"1\" STAGING_SHARED_MEMORY=\"1\" WINE_LARGE_ADDRESS_AWARE=\"1\" vblank_mode=\"0\" mesa_glthread=\"true\" && cd \"/home/maddog76/Wine-Launcher\" && cd \"/home/maddog76/Wine-Launcher/prefix/drive_c/Games/Age of Empires Definitive Edition\" &&  \"/home/maddog76/Wine-Launcher/wine/bin/wine\"  \"AoEDE.exe\" "

esync: up and running.

That's what it says,that happens when i launch the game load for few seconds but no new window opens and the Run stops..
To my eyes there isn't an error.
Guessing..are there missing some libraries?
I had installed 5.0.3 X86 and installed wine 5.22 X86-64 since X86 won't allow me even to launch the game,rebuilt the prefix  Windows 10 X86-64,saved the changes.
No errors or flashing info's on prefixes.

**Comment by HappyCampero76** [comment]
Console
×Close
[Wine Launcher] Run command:
 sh -c "export LD_LIBRARY_PATH=\"/home/maddog76/Wine-Launcher/bin/libs/i386:/home/maddog76/Wine-Launcher/bin/libs/x86-64:$LD_LIBRARY_PATH\" VK_LAYER_PATH=\"$VK_LAYER_PATH:/home/maddog76/Wine-Launcher/data/cache/implicit_layer.d\" XDG_CACHE_HOME=\"/home/maddog76/Wine-Launcher/data/cache\" WINE=\"wine\" WINE64=\"wine64\" WINEPREFIX=\"/home/maddog76/Wine-Launcher/prefix\" WINESERVER=\"wineserver\" WINEARCH=\"win32\" WINEDEBUG=\"-all\" WINESTART=\"C:\\windows\\command\\start.exe\" WINEDLLOVERRIDES=\"\" LC_ALL=\"it_IT.UTF-8\" WINEESYNC=\"1\" WINEFSYNC=\"1\" STAGING_SHARED_MEMORY=\"1\" WINE_LARGE_ADDRESS_AWARE=\"1\" vblank_mode=\"0\" mesa_glthread=\"true\" GALLIUM_HUD=\"simple,fps\" && cd \"/home/maddog76/Wine-Launcher\" && cd \"/home/maddog76/Wine-Launcher/prefix/drive_c/Games/home/maddog76/Wine-Launcher/data/games/7-Zip\" &&  \"wine\"  \"7z.exe\" "

sh: 1: cd: can't cd to /home/maddog76/Wine-Launcher/prefix/drive_c/Games/home/maddog76/Wine-Launcher/data/games/7-Zip
Gave up with Age of Empires and attempted to follow your instruction step by step with 7Zip folder....
moved as you said in the data/games/ folder,went to create the prefix as you said to Prefix > Games > Edit > Folder tab > Path (first field) > but the result its the same,cannot cd to 7zip folder.
Downloaded a new copy of start and deleted everything from previous installation, before running the new copy,moved the new copy in the same folder gave to start the permission to run as program,ran it,waited to create all folder,moved 7zip into data/games,created as you specified in your answer to Prefix > Games > Edit > Folder tab > Path (first field) > 7-Zip saved...
but the result is cannot run it.
One thing tho with the new installation of start i didn't apply the patch LAV Filters"but i am guessing means nothing with loading 7zip".

**Comment by hitman249** [comment]
You entered an absolute path in the path field
**/home/maddog76/Wine-Launcher/prefix/drive_c/Games** _/home/maddog76/Wine-Launcher/data/games/_ 7-Zip

Read the field hints carefully
Also there are examples
