### ISSUE TITLE
Поддержка PipeWire

### ISSUE THREAD

**Issue by EveKaczmarek** [hitman249/wine-launcher#21]
ArchLinux, удалён PulseAudio, установлен PipeWire и pipewire-pulse

Wine, запускаемый через лаунчер, не видит этого и загружает winealsa.drv
В то же время в системном Wine никаких проблем.
![Screenshot_20210215_120346](https://user-images.githubusercontent.com/52298587/107925759-c52ace00-6f6c-11eb-9912-5211e7f1990d.png)

**Comment by hitman249** [comment]
какие бинарники есть у этого PipeWire ?
нужно чтобы команда `command -v pipe-wire` (например) выдавала путь к этому файлу

**Comment by EveKaczmarek** [comment]
`/usr/bin/pipewire` и `/usr/bin/pipewire-pulse`

**Comment by hitman249** [comment]
добавил, проверяйте

**Comment by EveKaczmarek** [comment]
Спасибо. Работает.
