### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by AsciiWolf** [hitman249/wine-launcher#23]
Thanks for working on this new Wine launcher. Also, it's really great to see that someone still plays Lineage II and even on Linux! :-)

Are there any plans to package wine-launcher as a Flatpak and publish it on [Flathub](https://flathub.org)?

**Comment by hitman249** [comment]
Hello, this is at odds with the concept of this utility.
It is kept in place with every game and does not have a central installation location.
