### ISSUE TITLE
Проблема с символьными ссылками

### ISSUE THREAD

**Issue by EveKaczmarek** [hitman249/wine-launcher#24]
В последних версиях Wine TKG перестали определяться символьные ссылки в префиксе. Последней рабочей версией остался Wine 6.0.

Содержимое диска C: до обновления (wine-tkg 6.0.r0)
![изображение](https://user-images.githubusercontent.com/52298587/109540992-24cfc000-7abb-11eb-9c8e-fb5179496c44.png)

И после обновления (wine-tkg 6.3.r0)
![изображение](https://user-images.githubusercontent.com/52298587/109542410-ecc97c80-7abc-11eb-854b-6033164219da.png)

Понимаю, что скорее всего это не проблема лаунчера, просто на всякий случай.

**Comment by hitman249** [comment]
1) Есть ли у вас такое предупреждение? 
![2021-03-02_10-36](https://user-images.githubusercontent.com/1325326/109593828-4759eb80-7b44-11eb-831c-e3eeab955d7a.png)

2) Скиньте пожалуйста свой конфиг, раздел `Инструменты > Диагностика`
![2021-03-02_10-37](https://user-images.githubusercontent.com/1325326/109593949-838d4c00-7b44-11eb-9afe-57a1dbb86b75.png)

Proton TKG начиная с 6.1 требует Glibc выше версии 2.31

**Comment by EveKaczmarek** [comment]
1. Нет, такого предупреждения не было.

2.
```
---------------------------------------

Wine Launcher version: 1.4.47
RAM: 15943
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
GPU: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
GPU driver: nvidia, nvidia, 460.56
Distr: Arch rolling
Linux Kernel: Linux 5.10.17-126-tkg-upds x86_64
Arch: 64
Glibc: 2.33
X.Org: 1.20.10
Xrandr: 1.5.1
vm.max_map_count: 262144
Ulimit Soft: 1048576
Ulimit Hard: 1048576

---------------------------------------

[FAIL] [app] [32: miss] [64: miss] gamemode
[FAIL] [app] [32: miss] [64: miss] pulseaudio
[FAIL] [app] [32: miss] [64: miss] xlsfonts
[FAIL] [font] [32: miss] [64: miss] fonts-horai-umefont
[FAIL] [font] [32: miss] [64: miss] fonts-unfonts-core
[FAIL] [font] [32: miss] [64: miss] fonts-unfonts-extra
[FAIL] [font] [32: miss] [64: miss] fonts-wqy-microhei
[FAIL] [font] [32: miss] [64: miss] ttf-mscorefonts
[FAIL] [lib] [32: miss] [64: miss] libcapi20-3
[FAIL] [lib] [32: miss] [64: ok] libfuse2
[FAIL] [lib] [32: miss] [64: ok] libgsm1
[FAIL] [lib] [32: miss] [64: ok] libjpeg62
[FAIL] [lib] [32: miss] [64: miss] libncurses5
[FAIL] [lib] [32: miss] [64: miss] libncurses6
[FAIL] [lib] [32: miss] [64: miss] libncursesw5
[FAIL] [lib] [32: miss] [64: miss] libodbc1
[FAIL] [lib] [32: miss] [64: miss] libpcap0.8
[FAIL] [lib] [32: miss] [64: ok] libpng12
[FAIL] [lib] [32: miss] [64: miss] libsane1
[FAIL] [lib] [32: miss] [64: ok] libvkd3d
[FAIL] [lib] [32: miss] [64: ok] samba-libs
[OK] [app] binutils
[OK] [app] cabextract
[OK] [app] diff
[OK] [app] fc-list
[OK] [app] ffmpeg
[OK] [app] free
[OK] [app] fusermount
[OK] [app] glxinfo
[OK] [app] grep
[OK] [app] hostname
[OK] [app] icotool
[OK] [app] id
[OK] [app] ldconfig
[OK] [app] ldd
[OK] [app] locale
[OK] [app] lsmod
[OK] [app] lspci
[OK] [app] mksquashfs
[OK] [app] modinfo
[OK] [app] mount
[OK] [app] objdump
[OK] [app] p7zip
[OK] [app] patch
[OK] [app] ps
[OK] [app] sed
[OK] [app] tar
[OK] [app] tee
[OK] [app] unrar
[OK] [app] unzip
[OK] [app] winbind
[OK] [app] wine
[OK] [app] wrestool
[OK] [app] xrandr
[OK] [app] xz
[OK] [app] zip
[OK] [app] zstd
[OK] [lib] libFAudio
[OK] [lib] libasound2
[OK] [lib] libcups2
[OK] [lib] libdbus-1-3
[OK] [lib] libfontconfig1
[OK] [lib] libfreetype6
[OK] [lib] libgif7
[OK] [lib] libgl1
[OK] [lib] libglib2
[OK] [lib] libgnutls30
[OK] [lib] libgstreamer1.0
[OK] [lib] libgtk-3
[OK] [lib] libjpeg8
[OK] [lib] libmpg123
[OK] [lib] libncursesw6
[OK] [lib] libopenal1
[OK] [lib] libosmesa6
[OK] [lib] libpng16
[OK] [lib] libsdl2
[OK] [lib] libsm6
[OK] [lib] libtheora
[OK] [lib] libtiff5
[OK] [lib] libudev1
[OK] [lib] libv4l
[OK] [lib] libvorbis0a
[OK] [lib] libvulkan1
[OK] [lib] libxcb1
[OK] [lib] libxcomposite1
[OK] [lib] libxinerama1
[OK] [lib] libxrandr2
[OK] [lib] libxslt1.1
```

3. Да, префикс был неоднократно пересоздан.

**Comment by hitman249** [comment]
Попробовал на Manjaro, префикс создался корректно
1) Попробуйте обновиться на последнюю версию WL `1.4.49` ( `Помощь > Обновления` )
2) Убедитесь что у вас в системе отсутствует приложение `AppImageLauncher`

**Comment by EveKaczmarek** [comment]
Обновление не помогло, `AppImageLauncher` не установлен и не устанавливался.

Проблема с символьными ссылками проявляется именно на Wine 6.3, все ранние версии (6.0-6.2) работают корректно.
Так же были протестированы cборки Wine 6.3 `staging` и `staging-tkg` от Kron4ek, результат тот же.

Просмотр папки через `wineconsole` и `explorer` показал следующее:
![изображение](https://user-images.githubusercontent.com/52298587/109767677-d07a2c80-7bef-11eb-937d-65ccfbf32d20.png)

Символьные ссылки создаются, но очень странно. В `wineconsole` папки отображаются как ссылки, которые нельзя просмотреть командой `dir`, но можно зайти в них командой `cd`. При этом в `explorer` папки отображаются как файлы, с которыми ничего нельзя сделать.

Несмотря на эти проблемы, большая часть игр запускается и вполне полноценно работает. Некоторые из них падают, если им необходимо выйти за пределы своей директории.

**Comment by hitman249** [comment]
Похоже мы имеем дело с регрессией в самом Wine

**Comment by hitman249** [comment]
Ожидаем решение https://bugs.winehq.org/show_bug.cgi?id=50767

**Comment by hitman249** [comment]
фикс выкатили, но рабочий билд уже в 6.4 будет видимо
