### ISSUE TITLE
The shortcut does not start the application

### ISSUE THREAD

**Issue by begeeem0t** [hitman249/wine-launcher#30]
The shortcut created by wine-launcher launches wine-launcher itself, not the installed application. 
"./start --game game1" also launches wine-launcher

**Comment by hitman249** [comment]
It should be so.
The task of the WL is to calculate the time spent in the game.

**Comment by begeeem0t** [comment]
Is there a way to start the game immediately? If I'm not interested in counting the time spent in the game.

**Comment by hitman249** [comment]
No, WL's task is not only about time tracking.
But also in the initial preparation of the game for launch.
For example, if a game or wine is packaged in squashfs images, they must first be mounted.
Or, WL restores the screen resolution after finishing the game.

**Comment by begeeem0t** [comment]
But you don't have to show the GUI to do that. PlayOnLinux, for example, creates a shortcut that launches the application without showing the GUI of the PoL itself and requiring no extra action from the user.

**Comment by hitman249** [comment]
Hid the window of the launcher, check in the latest version

**Comment by begeeem0t** [comment]
The WL GUI is still running.
"./start --game2 --hide" also starts the WL GUI (

**Comment by hitman249** [comment]
Your command is incorrect.  
Correct command: `./start --game game5 --autostart standard --hide`  
Create a shortcut through a graphical interface

**Comment by begeeem0t** [comment]
Thank you! Saw the new options in the GUI. 
But wine-launcher GUI still appears for a moment, before the start of the game )
In the tiling window manager, it's pretty noticeable (

**Comment by hitman249** [comment]
Fixed, update to the latest version

**Comment by begeeem0t** [comment]
Great! Thank you!
