### ISSUE TITLE
Не создаётся префикс

### ISSUE THREAD

**Issue by sergun123** [hitman249/wine-launcher#31]
Я устанавливаю Proton GE и меняю префикс на 64бит. Нажимаю пересоздать и на этом всё, прога виснет, бесконечное создание.

**Comment by hitman249** [comment]
Это проблема 6+ той версии proton, пробуйте более старые версии
WL тут не виноват

**Comment by sergun123** [comment]
Я попробовал другую версию - Wine-tkg x64 от kron4ek, то же самое.

**Comment by sergun123** [comment]
Нет, извиняюсь, префикс создался, хоть и долго. Но надпись "префикс не совместим с текущим Wine" не исчезает. Я пытался создать префикс и x86 и x64, без разницы. Что я делаю не так ?

**Comment by sergun123** [comment]
Перезагрузился и всё заработало
