### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by glmsmoura** [hitman249/wine-launcher#36]
I was searching for wine stuff on reddit and found this project! Really liked it, seems beautiful and direct.

Do you have any plans to release it in AUR? Would be really nice to have it.

**Comment by hitman249** [comment]
This program can be compared to the script for starting the game with wine, which is part of this game.  
The program that will be part of the game cannot be distributed in any repositories.

**Comment by hitman249** [comment]
@yochananmarqos 
You will have as many copies of WL as you have games.
WL is not installed globally, it is copied locally to every game.
