### ISSUE TITLE
Trouble with USB Generic Joystick

### ISSUE THREAD

**Issue by CocoCocoAlx** [hitman249/wine-launcher#42]
I cannot connect or configure my USB joystick. It is known that there is a problem with USB joysticks that can be solved by disabling one of the drivers detected by Wine. But I can't access that configuration menu, how could I run "wine control" inside my Wine profile? Thanks for your work

**Comment by hitman249** [comment]
I am not responsible for the work of the gamepads in Wine as it is a third-party software.  
But WL also has its own implementation to work with gamepads not related to Wine.
See
![Gamepads](https://raw.githubusercontent.com/hitman249/wine-launcher/master/gamepads.gif)

**Comment by CocoCocoAlx** [comment]
Yes, I found the option hours after asking the question, thank you. It has been very helpful. I close the thread.
