### ISSUE TITLE
Отсутствует лицензия

### ISSUE THREAD

**Issue by gavr123456789** [hitman249/wine-launcher#5]

**Comment by hitman249** [comment]
На исходный код?
эта ? https://github.com/hitman249/wine-launcher/blob/master/src/src/locales/ru.js#L266

**Comment by develop7** [comment]
Сойдёт. Проблема с ней в том, что она закопана в файле с локалью, и не видна сходу (и, в частности, не распознаётся гитхабом), что наглядно демонстрирует данное issue.

**Comment by hitman249** [comment]
добавил
