### ISSUE TITLE
Указание пути к исполняемому файлу

### ISSUE THREAD

**Issue by Helg1980** [hitman249/wine-launcher#9]
Добрый день!
Программа не плохая, но так и не смог разобраться как указать путь к исполняемому файлу. 
Так же нет возможности установить последнюю версию Wine 5.10, хотя она уже доступна для загрузки из Github.

**Comment by hitman249** [comment]
Доюрый день.
Скиньте ссылку на собранную версию wine 5.10 и я добавлю этот репозиторий в WL-е.

Путь к испольняемому файлу состоит из 3-х частей

1 часть находится в настройках префикса, по умолчанию там уже предзабито значение к `C:\Games`  (в настройках Папка с играми: Games)  
2 и 3 части находятся в настройках игры  
Т.е. там нужно указывать остаточный путь внутри папки `C:\Games` к папке в котором лежит `exe` файл, например `Epic Games/Launcher/Portal/Binaries/Win32` и в отдельном поле само имя `exe` файла например `EpicGamesLauncher.exe`  
При запуске программой эти 3 поля сложатся и получится единый путь  
`C:\Games` + `Epic Games\Launcher\Portal\Binaries\Win32` + `EpicGamesLauncher.exe`

**Comment by Helg1980** [comment]
Спасибо!

Вот ссылка на репозиторий:

https://github.com/wine-staging/wine-staging/archive/v5.10.tar.gz

**Comment by hitman249** [comment]
это не собранная версия

**Comment by Helg1980** [comment]
Тогда это проблема. Думал в таком виде можно добавлять.

**Comment by hitman249** [comment]
>  Смогу собранный для Arch Linux через пару дней скинуть ссылку.

это не имеет смысла, т.к. хранить этот файл данному проекту попросту негде, как и идти в сторону развития появления сайта, какой-либо базы знаний(или скриптов) или wine репозитория в виду отсутствия финансирования (как минимум на текущий момент), все эти опции требуют надёжного хостинга, который стоит денег  

но ничего))) по этой причине WL проинтегрирован с кучей сторонных репозиториев (со всеми которых удалось обнаружить)  
поэтому здесь 2 выхода, тот что выше и просто ждать пока кто-нибудь из 6 репозиториев не выпустит свежий wine
ну и полумера, найти ещё более оперативный репозиторий
